### ISSUE TITLE
similarity measure

### ISSUE THREAD

**Issue by michalovadek** [bnosac/word2vec#5]
I think typically NLP applications use cosine similarity to measure proximity between vectors, especially in the context of embeddings. The fact that `word2vec::word2vec_similarity()` does not implement cosine similarity might surprise quite a few users. I would recommend switching to cosine similarity.

```{r}
m <- matrix(data = c(1,2,3,1,2,3,1,4,99), nrow = 3, ncol = 3, byrow = T)

## here are two efficient ways to implement cosine similarity
## from https://stats.stackexchange.com/questions/31565/compute-a-cosine-dissimilarity-matrix-in-r

res1 <- m %>% 
  {. / sqrt(rowSums(. * .))} %>% 
  {. %*% t(.)}

cos.sim=function(ma, mb){
  mat=tcrossprod(ma, mb)
  t1=sqrt(apply(ma, 1, crossprod))
  t2=sqrt(apply(mb, 1, crossprod))
  mat / outer(t1,t2)

res2 <- cos.sim(m,m)

res1
res2

## compare with

word2vec::word2vec_similarity(c(1,2,3),c(1,2,3))

## or

word2vec::word2vec_similarity(c(0.1,0.2,0.3),c(0.1,0.2,0.3))

```

**Comment by jwijffels** [comment]
The implementation in the R pkg follows the logic of https://github.com/bnosac/word2vec/blob/f3e2bd187e68d88c6ee45fbada4419979da11efd/src/word2vec/include/word2vec.hpp#L178
Maybe @maxoodf could comment on the reason of preferring inner products?

**Comment by jwijffels** [comment]
I've added the 'cosine' option to word2vec_similarity. If you specify type = "cosine", you get that similarity instead of the default.
