### ISSUE TITLE
model is error

### ISSUE THREAD

**Issue by niutyut** [bnosac/word2vec#8]
(1)first is right
sentences.join=c("子 夏 问 曰 巧 笑 倩 兮 美 目 盼 兮 素 ","以 为 绚 兮 何 谓 也 子 曰 绘 事 后 素 曰 礼")
model <- word2vec(x = sentences.join, type="cbow",min_count = 1,window =8 )  

(2) second is error.
sentences.join=paste(c("子 夏 问 曰 巧 笑 倩 兮 美 目 盼 兮 素") ,c("以 为 绚 兮 何 谓 也 子 曰 绘 事 后 素 曰 礼"),sep=" ")
model <- word2vec(x = sentences.join, type="cbow",min_count = 1,window =8 )

Training failed: fileMapper: 子 夏 问 曰 巧 笑 倩 兮 美 目 盼 兮 素  以 为 绚 兮 何 谓 也 子 曰 绘 事 后 素 曰 礼 - No such file or directory

By combining the two previous string vectors into one vector, the model is wrong.why?

**Comment by jwijffels** [comment]
The first argument to word2vec is either a file or a character vector of length > 1. 
If you provide a character vector of length 1, it is assumed you provided the path to a file.

**Comment by niutyut** [comment]
but my file is a sentence ，its length is very long,how to use your word2vec？

**Comment by niutyut** [comment]
but my file is read as a  character vector，
x=readr::read_csv(”d:\myfile.txt”，col_names = FALSE)
x=“子 夏 问 曰 巧 笑 倩 兮 美 目 盼 兮 素 以 为 绚 兮 何 谓 也 子 曰 绘 事 后 素 曰 礼”
model <- word2vec(x =x, type="cbow",min_count = 1,window =8 )
error is below：
Training failed: fileMapper: 子 夏 问 曰 巧 笑 倩 兮 美 目 盼 兮 素 以 为 绚 兮 何 谓 也 子 曰 绘 事 后 素 曰 礼 - No such file or directory

how to use your word2vec？

**Comment by jwijffels** [comment]
word2vec(x ="d:\myfile.txt", type="cbow",min_count = 1,window =8 )

**Comment by niutyut** [comment]
but my file is read as a character vector，
x=readr::read_csv(”d:\myfile.txt”，col_names = FALSE)
print（x）
x is “子 夏 问 曰 巧 笑 倩 兮 美 目 盼 兮 素 以 为 绚 兮 何 谓 也 子 曰 绘 事 后 素 曰 礼”
model <- word2vec(x =x, type="cbow",min_count = 1,window =8 )
error is below：
Training failed: fileMapper: 子 夏 问 曰 巧 笑 倩 兮 美 目 盼 兮 素 以 为 绚 兮 何 谓 也 子 曰 绘 事 后 素 曰 礼 - No such file or directory

how to use your word2vec？

**Comment by jwijffels** [comment]
model <- word2vec(x ="d:\myfile.txt", type="cbow",min_count = 1,window =8 )

**Comment by niutyut** [comment]
but myfile is read as a data.frame. format is below:
DB_sentences<-readr::read_csv( "pooled.txt"),col_names = FALSE);
  sentences=DB_sentences$X2
  sentences<-gsub("\\.","",sentences)
  sentences<-gsub("\\,","",sentences)
print(sentences)
sentences is "子 夏 问 曰 巧 笑 倩 兮 美 目 盼 兮 素 以 为 绚 兮 何 谓 也 子 曰 绘 事 后 素 曰 礼"
model <- word2vec(x =sentences, type="cbow",min_count = 1,window =8 )
error is below:
Training failed: fileMapper: 子 夏 问 曰 巧 笑 倩 兮 美 目 盼 兮 素 以 为 绚 兮 何 谓 也 子 曰 绘 事 后 素 曰 礼 - No such file or directory

my DB_sentences has two variables，one is X1 ，another is X2，X2 contains variables that are the objects to be processed.so You can no longer read files directly from the model. 【model <- word2vec(x ="d:\myfile.txt", type="cbow",min_count = 1,window =8 )】 is not suitable,how to do it?

**Comment by jwijffels** [comment]
writeLines(text = sentences, con = "traindata.txt", useBytes = TRUE)
model <- word2vec(x ="traindata.txt", type="cbow",min_count = 1,window =8 )
