### ISSUE TITLE
compare the similarity of two words

### ISSUE THREAD

**Issue by niutyut** [bnosac/word2vec#9]
hello,
i have some problems,can you help me?
1. compare the similarity of two words, please ask word2vec how to do it.
For example, the similarity of negro and struggle, because this determines the evolution of the idea of the struggle of blacks for liberation.
2. compare the similarity of two groups of words, how does word2vec do it.
For example, the degree of similarity between c("negro", "negroes", "negro") and c("revolution", "movement"). This is a comparison with a similar set of concepts.
![image](https://user-images.githubusercontent.com/7684989/134752005-8c98f51f-985f-46de-9f90-76862528e04f.png)

I found the solution in a package called library(wordVectors), but this package does not support Chinese. So I would like to consult you about the implementation of this word2vec package.
Below is the case code of wordVectors package. You can check it out.

https://github.com/kkdey/Black_magazines

**Comment by jwijffels** [comment]
Have you already looked to the documentation of ?word2vec_similarity and ?predict.word2vec
These functions provide anything you need to calculate word distances

**Comment by niutyut** [comment]
thank you！i will study word2vec_similarity and predict.word2vec。

**Comment by niutyut** [comment]
word2vec_similarity(x, x)
           gastheer gastvrouw     kamer
gastheer  0.5477779 0.6265383 0.6370294
gastvrouw 0.6265383 0.7834447 0.7475214
kamer     0.6370294 0.7475214 0.8582011

 gastheer and gastheer is same word，its similarity should be 1，why is 0.5477779？ is this error？

**Comment by niutyut** [comment]
word2vec_similarity(x, x)
                gastheer gastvrouw     kamer
gastheer  0.5477779 0.6265383 0.6370294
gastvrouw 0.6265383 0.7834447 0.7475214
kamer     0.6370294 0.7475214 0.8582011

 gastheer and gastheer is same word，its similarity should be 1，why is 0.5477779？ is this error？

**Comment by niutyut** [comment]
word2vec_similarity(x, x)
----------- gastheer gastvrouw     kamer
gastheer  0.5477779 0.6265383 0.6370294
gastvrouw 0.6265383 0.7834447 0.7475214
kamer     0.6370294 0.7475214 0.8582011

 gastheer and gastheer is same word，its similarity should be 1，why is 0.5477779？ is this error？

**Comment by niutyut** [comment]
word2vec_similarity(x, x)
-----------gastheer gastvrouw kamer
gastheer 0.5477779 0.6265383 0.6370294
gastvrouw 0.6265383 0.7834447 0.7475214
kamer 0.6370294 0.7475214 0.8582011

gastheer and gastheer is same word，its similarity should be 1，why is 0.5477779？ is this error？

**Comment by jwijffels** [comment]
The best thing to understand what word2vec_similarity dot product and cosine similarity do is read the documentation.

**Comment by jwijffels** [comment]
closing as all is in the documentation
